# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://lchamberland.github.io/
title: Lisa Chamberland, PhD
email: chamberlandlisa8@gmail.com
author: Lisa Chamberland
description: > # "Write an awesome description for your new site here. 
  Welcome to the website for Lisa Chamberland, PhD
copyright: 'Copyright &copy; 2025 Lisa Cahmberland. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=xfASmp4AAAAJ&hl=en
  - title: github
    url: https://github.com/lchamberland
  - title: linkedin
    url: https://www.linkedin.com/in/lisa-chamberland-4238a022/
